name = "hummingbard"
mode = "development"
# youtube_key ="your-youtube-api-key"

[client]
domain = "hummingbard.com"
port = ":8999"
cookie_name = "hummingbard"
secure_cookie = "something_random"

[matrix]
server = "localhost.com"
port = 8008
password = "CaR6hxVWKBzYn"

[db]
client = "" # postgres connection string
dendrite_user_api_accounts = "" # Dendrite userapi_accounts DB

[redis]
address = "localhost:6379"
password = "redis"
db = 1

[spaces]
prefix = "org.matrix.msc1772.space"

[auth]
verify_email = true
disable_registration = false
disable_federated_login = false
disable_profile_creation = false
shared_secret = "" #must match with shared_secret in dendrite.yaml

[privacy]
disable_public = false

[email]
server = ""
port =  587
username = ""
password = ""
